/**
 * @file useProjectList.ts
 * 
 * @summary Custom hooks for managing projects and project state
 * @remarks
 * - Loads project list
 * - Creates new projects
 * - Deletes projects
 * - Renames projects
 * - Imports projects from file content
 * 
 * @exports CreateProjectInput - Type for input data required to create a new project
 * @exports useProjectList - Hook for managing project list state and operations
 */


// External dependencies
import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// Internal dependencies
import { apiClient } from '@/services/api-client';

// Types
import type { Project } from '@/hooks/useProjectView';


/**
 * @template CreateProjectInput
 * @summary The input type for creating a new project.
 * @remarks
 * The 'Project' type describes the full structure of the project.
 * However, not all fields are required when creating a new project.
 * Here, we use 'Pick' to select the 'name' field as mandatory.
 * Then, we used 'Partial' to identify optional fields.
 * The 'id' field is not included at all, as it is generated by the backend.
 */
export type CreateProjectInput =
  Pick<Project, 'name'> &
  Partial<Pick<Project, 'description' | 'center_lat' | 'center_lon' | 'zoom_level'>>;


/**
 * @template UseProjectListReturn
 * @summary Return type for useProjectList hook.
 * @remarks
 * This interface defines the structure of the object returned by the useProjectList hook,
 * including the list of projects, loading states, and functions for managing projects.
 * 
 * @property {Project[]} projects - List of projects.
 * @property {boolean} loading - Loading state for project list (true while fetching projects).
 * @property {boolean} isImporting - Importing state for project import (true while importing a project).
 * @property {() => Promise<void>} loadProjects - Function to load all projects.
 * @property {(projectData: CreateProjectInput) => Promise<void>} createProject - Function to create a new project.
 * @property {(id: number) => Promise<void>} deleteProject - Function to delete a project.
 * @property {(id: number, name: string) => Promise<void>} renameProject - Function to rename a project.
 * @property {(fileContent: string) => Promise<void>} importProject - Function to import a project from a JSON file.
 */
type UseProjectListReturn = {
  projects: Project[];
  loading: boolean;
  isImporting: boolean;
  loadProjects: () => Promise<void>;
  createProject: (projectData: CreateProjectInput) => Promise<void>;
  deleteProject: (id: number) => Promise<void>;
  renameProject: (id: number, name: string) => Promise<void>;
  importProject: (fileContent: string) => Promise<void>;
}


/**
 * @function useProjectList
 * @summary Custom hook for managing project list state and operations.
 * @remarks
 * Provides functions to:
 * - Load projects
 * - Create new projects
 * - Delete projects
 * - Rename projects
 * - Import projects from a JSON file
 * 
 * @returns Project list state and operations
 */
export const useProjectList = (): UseProjectListReturn => {
    const navigate = useNavigate();

    // State: List of projects, based on the 'Project' type
    const [projects, setProjects] = useState<Project[]>([]);

    // State: Flags for loading and importing; True while loading/importing, false otherwise
    const [loading, setLoading] = useState(true);
    const [isImporting, setIsImporting] = useState(false);


    /**
     * @function loadProjects
     * @summary Loads the list of projects from the backend API.
     * @remarks
     * Runs initially when the component mounts.
     * Runs again if a project is imported.
     * 
     * The loading state is already true when the component mounts.
     * 1. Fetches projects from the API and updates the state.
     * 2. Sets loading state to false after fetching is complete.
     * 
     * @returns void
     */
    const loadProjects = useCallback(async (): Promise<void> => {
        try {
            // Fetch projects from API, and update state with the fetched data
            const data = await apiClient.listProjects();
            setProjects(data);
        } catch (error) {
            console.error('Failed to load projects:', error);
        } finally {
            // Set loading to false after fetching is complete (whether successful or not)
            setLoading(false);
        }
    }, []);


    /**
     * @function createProject
     * @summary Create a new project
     * @remarks
     * On success, adds the new project to the projects state and navigates to its page.
     * 'navigate' is in the dependency array to avoid closing over a stale instance of the navigate function.
     * 1. Creates a new project via the API
     * 2. Update the project state with the new project
     * 3. Navigate to the new project's page
     * 
     * @param projectData - Data for the new project (excluding ID)
     * @returns void
     */
    const createProject = useCallback(async (
        projectData: CreateProjectInput
    ): Promise<void> => {
        try {
            // Create project via API
            const created = await apiClient.createProject(projectData);

            /*
             * Update the projects state with the newly created project.
             * This only updates with the new information, and retains all previous values
             * Finally, navigate to the new project's page using its ID.
             */
            setProjects((prev) => [...prev, created]);
            navigate(`/projects/${created.id}`);
        } catch (error) {
            console.error('Failed to create project:', error);
            throw error;
        }
    }, [navigate]);


    /**
     * @function deleteProject
     * 
     * @summary Deletes a project by ID via the backend API.
     * @remarks
     * On success, removes the project from the projects state.
     * 1. Prompt the user for confirmation
     * 2. Delete the project via the API
     * 3. Update the project state by removing the deleted project
     *
     * @param id - ID of the project to delete
     * @returns void
     */
    const deleteProject = useCallback(async (
        id: number
    ): Promise<void> => {
        // Pop up a confirmation window before deleting the project
        if (!window.confirm('Are you sure you want to delete this project?')) {
            return;
        }

        try {
            // Delete project via API
            await apiClient.deleteProject(id);

            /*
             * Updates the project's state by filtering out the deleted project.
             * This creates a new array that includes all projects except the one with the matching ID.
             * The state is then updated with this new array.
             */
            setProjects((prev) => prev.filter((p) => p.id !== id));
        } catch (error) {
            console.error('Failed to delete project:', error);
            throw error;
        }
    }, []);


    /**
     * @function renameProject
     * 
     * @summary Renames a project via the backend API.
     * @remarks
     * On success, updates the project's name in the projects state.
     * 1. Rename the project via the API
     * 2. Update the project state
     *
     * @param id - ID of the project to rename
     * @param name - New name for the project
     * @returns void
     */
    const renameProject = useCallback(async (
        id: number,
        name: string
    ): Promise<void> => {
        try {
            // Rename project via API
            const updated = await apiClient.updateProject(id, { name });

            // Update state with renamed project
            setProjects((prev) =>
                prev.map((p) => (p.id === id ? updated : p))
            );
        } catch (error) {
            console.error('Failed to rename project:', error);
            throw error;
        }
    }, []);


    /**
     * @function importProject
     * 
     * @summary Imports a project from file content via the backend API.
     * @remarks
     * On success, adds the imported project to the projects state and navigates to its page.
     * 1. Set importing state flag
     * 2. Load the JSON data from the file content
     * 3. Send the data to the API for importing
     * 4. Refresh the project list by loading the projects again from the API
     * 5. Navigate to the newly imported project's page
     * 
     * loadProjects and navigate are in the dependency array to avoid closing over stale instances of these functions.
     *
     * @param fileContent - Content of the project file to import
     * @returns void
     */
    const importProject = useCallback(async (
        fileContent: string
    ): Promise<void> => {
        /*
         * Set the importing state to true.
         * This enables us to show a loading indicator and disable UI elements while the import is in progress.
         */
        setIsImporting(true);

        try {
            // Load the JSON data from the file content, and send it to the API for importing
            const importData = JSON.parse(fileContent);
            const importedProject = await apiClient.importProject(importData);

            /*
             * Refresh the project list by loading the projects again from the API.
             * Then, navigate to the newly imported project's page using its ID.
             */
            await loadProjects();
            navigate(`/projects/${importedProject.id}`);
        } catch (error) {
            console.error('Failed to import project:', error);
            throw error;
        } finally {
            // Disable the importing state, regardless of success or failure
            setIsImporting(false);
        }
    }, [loadProjects, navigate]);


    // Load projects on component mount
    useEffect(() => {
        loadProjects();
    }, [loadProjects]);


    /**
     * Return the project list state and operations.
     */
    return {
        projects,
        loading,
        isImporting,
        loadProjects,
        createProject,
        deleteProject,
        renameProject,
        importProject,
    };
};
